services:
  db:
    container_name: postgres
    image: postgres:16.6-alpine3.21
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: default-user 
      POSTGRES_PASSWORD: default-password
      POSTGRES_DB: api-db
    volumes:
      - db-volume:/var/lib/postgresql/data
volumes:
  db-volume:
